### ISSUE TITLE
NVMe controller will not reset

### ISSUE THREAD

**Issue by Furao** [RTSYork/nvme-microblaze#2]
I have been trying to use this code for my own design with a microblaze on a zcu102. I have gotten it to build and run and I can read values from the device registers. I get values I would expect during `nvme_create()`. However, in `nvme_ctlr_enable()` the controller never comes back on. Have you seen this behavior at all?

It would also be helpful if you could let me know exactly how you chose the values for the following
```
MEM_BASE_M
MEM_BASE_PCI
```

**Comment by RussellJoyce** [comment]
I think those memory address values came from how I had memory mapped in my specific Vivado design, but I'm not 100% sure off the top of my head. I also think the commented-out values above them in `params.h` were left over from some experimentation with putting the data in the higher memory areas on the ZCU102 and masking out address bits in the hardware to allow the 32-bit MicroBlaze to address them, or possibly from some experimentation with PAE. I'll take a deeper look at my design and try to figure it out for sure...

Talking of which, I've been meaning for a while to upload the Vivado hardware design I used with this, so now you've given me a good excuse to actually do that! I'll try to dig it out this week and add it to the repo, and hopefully it will be helpful.

I've also only ever tested this code with an Intel SSD 750 PCIe set to 4KiB blocks, so it's possible that other SSDs or block sizes might not work without modification.

**Comment by Furao** [comment]
Thank you for the feedback. I was integrating this with a different PCIe driver and I actually had a bug in there. The bridge wasn't getting enabled, so that would explain it. I can now successfully run the tests. I still think it would be helpful if you were to upload your hardware design for anyone else that might be trying to use this example.

Thanks for the implementation!
